# Generated by Django 3.0 on 2019-12-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ref_name', models.CharField(max_length=50)),
                ('data_ref_project', models.CharField(max_length=50)),
                ('json_data', models.TextField()),
            ],
            options={
                'unique_together': {('data_ref_name', 'data_ref_project')},
            },
        ),
    ]
