# Generated by Django 3.0 on 2019-12-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='dataref',
            name='order_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dataref',
            name='data_ref_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dataref',
            name='data_ref_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_view.Project'),
        ),
    ]
