# Generated by Django 3.0 on 2019-12-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_view', '0003_auto_20191223_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataref',
            name='type_of_data',
            field=models.CharField(choices=[('Double_Arr', 'Double_Arr'), ('Integer_Arr', 'Integer_Arr'), ('Double', 'Double'), ('Int', 'Int')], default='Int', max_length=11),
        ),
    ]
