# Generated by Django 3.0 on 2019-12-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_view', '0004_dataref_type_of_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataref',
            name='refresh_time',
            field=models.IntegerField(default=10),
        ),
    ]
