# Generated by Django 3.0 on 2019-12-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_view', '0007_dataref_type_of_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataref',
            name='type_of_display',
            field=models.CharField(choices=[('Graph_Display', 'Graph_Display'), ('Raw_Display', 'Raw_Display')], default='Raw_Display', max_length=30),
        ),
    ]
